name: Check PR
on: [pull_request]

env:
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.UTOPIA_RISE_GPG_PRIVATE_KEY_ASCII }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.UTOPIA_RISE_GPG_KEY_PASSPHRASE }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.UTOPIA_RISE_MAVEN_CENTRAL_PORTAL_TOKEN_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.UTOPIA_RISE_MAVEN_CENTRAL_PORTAL_TOKEN_PASSWORD }}
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          wrapper-directory: kotlin-preprocessors/
          build-root-directory: kotlin-preprocessors/
      - name: Tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
          wrapper-directory: kotlin-preprocessors/
          build-root-directory: kotlin-preprocessors/
